export const STICKER_URLS = {
  leaf:"/assets/forest/stickers/leaf.png", mushroom:"/assets/forest/stickers/mushroom.png",
  butterfly:"/assets/forest/stickers/butterfly.png", sunflower:"/assets/forest/stickers/sunflower.png",
  ladybug:"/assets/forest/stickers/ladybug.png", frog:"/assets/forest/stickers/frog.png",
  deer:"/assets/forest/stickers/deer.png", owl:"/assets/forest/stickers/owl.png",
  acorn2:"/assets/forest/stickers/acorn.png", pinecone2:"/assets/forest/stickers/pinecone.png",
  fox:"/assets/forest/stickers/fox.png", hedgehog:"/assets/forest/stickers/hedgehog.png",
  berries:"/assets/forest/stickers/berries.png", snail:"/assets/forest/stickers/snail.png",
  toadstool:"/assets/forest/stickers/toadstool.png", moss:"/assets/forest/stickers/moss.png",
  shell:"/assets/ocean/stickers/shell.png", fish:"/assets/ocean/stickers/fish.png",
  dolphin:"/assets/ocean/stickers/dolphin.png", crab:"/assets/ocean/stickers/crab.png",
  blowfish:"/assets/ocean/stickers/blowfish.png", starfish:"/assets/ocean/stickers/starfish.png",
  octopus:"/assets/ocean/stickers/octopus.png", whale:"/assets/ocean/stickers/whale.png",
  seahorse:"/assets/ocean/stickers/seahorse.png", jellyfish:"/assets/ocean/stickers/jellyfish.png",
  turtle:"/assets/ocean/stickers/turtle.png", coral:"/assets/ocean/stickers/coral.png",
  pearl:"/assets/ocean/stickers/pearl.png", sailboat:"/assets/ocean/stickers/sailboat.png",
  lighthouse:"/assets/ocean/stickers/lighthouse.png", wave2:"/assets/ocean/stickers/wave.png",
  sparkles:"/assets/anime/stickers/sparkles.png", heartpink:"/assets/anime/stickers/heart.png",
  star2:"/assets/anime/stickers/star.png", catface:"/assets/anime/stickers/cat.png",
  rainbowstar:"/assets/anime/stickers/rainbow.png", dango:"/assets/anime/stickers/dango.png",
  chibi:"/assets/anime/stickers/chibi.png", sakuraPetal:"/assets/anime/stickers/sakura_petal.png",
  animeEyes:"/assets/anime/stickers/eyes.png", speedlines:"/assets/anime/stickers/speedlines.png",
  blushing:"/assets/anime/stickers/blush.png", sword2:"/assets/anime/stickers/sword.png",
  ramen:"/assets/anime/stickers/ramen.png", catears:"/assets/anime/stickers/catears.png",
  animeHeart:"/assets/anime/stickers/animeheart.png", shuriken:"/assets/anime/stickers/shuriken.png",
  pumpkin:"/assets/halloween/stickers/pumpkin.png", ghost:"/assets/halloween/stickers/ghost.png",
  bat:"/assets/halloween/stickers/bat.png", skull:"/assets/halloween/stickers/skull.png",
  witch:"/assets/halloween/stickers/witch.png", cauldron:"/assets/halloween/stickers/cauldron.png",
  blackcat:"/assets/halloween/stickers/blackcat.png", spider:"/assets/halloween/stickers/spider.png",
  spiderweb:"/assets/halloween/stickers/web.png", moon2:"/assets/halloween/stickers/moon.png",
  frankenstein:"/assets/halloween/stickers/frankenstein.png", vampire:"/assets/halloween/stickers/vampire.png",
  potion:"/assets/halloween/stickers/potion.png", eyeball:"/assets/halloween/stickers/eyeball.png",
  bonez:"/assets/halloween/stickers/bones.png", coffin:"/assets/halloween/stickers/coffin.png",
  blossom:"/assets/sakura/stickers/blossom.png", rosered:"/assets/sakura/stickers/rose.png",
  tulip:"/assets/sakura/stickers/tulip.png", bow:"/assets/sakura/stickers/bow.png",
  peach:"/assets/sakura/stickers/peach.png", fan:"/assets/sakura/stickers/fan.png",
  torii:"/assets/sakura/stickers/torii.png", fuji:"/assets/sakura/stickers/fuji.png",
  maneki:"/assets/sakura/stickers/maneki.png", origami:"/assets/sakura/stickers/origami.png",
  matcha:"/assets/sakura/stickers/matcha.png", onigiri:"/assets/sakura/stickers/onigiri.png",
  planet:"/assets/galaxy/stickers/planet.png", rocket:"/assets/galaxy/stickers/rocket.png",
  ufo:"/assets/galaxy/stickers/ufo.png", comet:"/assets/galaxy/stickers/comet.png",
  moon:"/assets/galaxy/stickers/moon.png", alien:"/assets/galaxy/stickers/alien.png",
  gamepad:"/assets/pixel/stickers/gamepad.png", joystick:"/assets/pixel/stickers/joystick.png",
  gem:"/assets/pixel/stickers/gem.png", sword:"/assets/pixel/stickers/sword.png",
  trophy:"/assets/pixel/stickers/trophy.png", pacman:"/assets/pixel/stickers/monster.png",
  pixelHeart:"/assets/pixel/stickers/heart.png", pixelStar:"/assets/pixel/stickers/star.png",
  pixelCoin:"/assets/pixel/stickers/coin.png", mushblock:"/assets/pixel/stickers/mushroom.png",
  pixelCloud:"/assets/pixel/stickers/cloud.png", bomb:"/assets/pixel/stickers/bomb.png",
  lightning2:"/assets/pixel/stickers/lightning.png", pixelCastle:"/assets/pixel/stickers/castle.png",
  ghost2:"/assets/pixel/stickers/ghost.png", pixelCrown:"/assets/pixel/stickers/crown.png",
  fallleaf:"/assets/autumn/stickers/leaf.png", mapleleaf:"/assets/autumn/stickers/maple.png",
  chestnut:"/assets/autumn/stickers/chestnut.png", haystack:"/assets/autumn/stickers/wheat.png",
  apple:"/assets/autumn/stickers/apple.png", scarecrow:"/assets/autumn/stickers/pumpkin.png",
  acorn:"/assets/autumn/stickers/acorn.png", mushroom2:"/assets/autumn/stickers/mushroom.png",
  squirrel:"/assets/autumn/stickers/squirrel.png", raindrop:"/assets/autumn/stickers/raindrop.png",
  candle:"/assets/autumn/stickers/candle.png", pie:"/assets/autumn/stickers/pie.png",
  hotcoffee:"/assets/autumn/stickers/coffee.png", pinecone:"/assets/autumn/stickers/pinecone.png",
  sweater:"/assets/autumn/stickers/sweater.png", pumpkinpie:"/assets/autumn/stickers/pumpkinpie.png",
  mirrorball:"/assets/disco/stickers/mirrorball.png", headphones:"/assets/disco/stickers/headphones.png",
  microphone:"/assets/disco/stickers/microphone.png", vinyl:"/assets/disco/stickers/vinyl.png",
  disco_star:"/assets/disco/stickers/star.png", dancer:"/assets/disco/stickers/dancer.png",
  neonlights:"/assets/disco/stickers/neonlights.png", confetti:"/assets/disco/stickers/confetti.png",
  rollerskate:"/assets/disco/stickers/rollerskate.png", taperecorder:"/assets/disco/stickers/tape.png",
  boombox:"/assets/disco/stickers/boombox.png", diamond:"/assets/disco/stickers/diamond.png",
  lightbeam:"/assets/disco/stickers/lightbeam.png", glitterball:"/assets/disco/stickers/glitterball.png",
  afro:"/assets/disco/stickers/afro.png", sunglasses:"/assets/disco/stickers/sunglasses.png",
  musicnotes:"/assets/music/stickers/notes.png", guitar:"/assets/music/stickers/guitar.png",
  piano:"/assets/music/stickers/piano.png", trumpet:"/assets/music/stickers/trumpet.png",
  violin:"/assets/music/stickers/violin.png", drums:"/assets/music/stickers/drums.png",
};

export const STICKERS_PER_THEME = {
  forest:    ["leaf","mushroom","butterfly","sunflower","ladybug","frog","deer","owl","acorn2","pinecone2","fox","hedgehog","berries","snail","toadstool","moss"],
  ocean:     ["shell","fish","dolphin","crab","blowfish","starfish","octopus","whale","seahorse","jellyfish","turtle","coral","pearl","sailboat","lighthouse","wave2"],
  anime:     ["sparkles","heartpink","star2","catface","rainbowstar","dango","chibi","sakuraPetal","animeEyes","speedlines","blushing","sword2","ramen","catears","animeHeart","shuriken"],
  halloween: ["pumpkin","ghost","bat","skull","witch","cauldron","blackcat","spider","spiderweb","moon2","frankenstein","vampire","potion","eyeball","bonez","coffin"],
  sakura:    ["blossom","rosered","tulip","bow","peach","fan","torii","fuji","maneki","origami","matcha","onigiri"],
  galaxy:    ["planet","rocket","ufo","comet","moon","alien"],
  pixel:     ["gamepad","joystick","gem","sword","trophy","pacman","pixelHeart","pixelStar","pixelCoin","mushblock","pixelCloud","bomb","lightning2","pixelCastle","ghost2","pixelCrown"],
  autumn:    ["fallleaf","mapleleaf","chestnut","haystack","apple","scarecrow","acorn","mushroom2","squirrel","raindrop","candle","pie","hotcoffee","pinecone","sweater","pumpkinpie"],
  disco:     ["mirrorball","headphones","microphone","vinyl","disco_star","dancer","neonlights","confetti","rollerskate","taperecorder","boombox","diamond","lightbeam","glitterball","afro","sunglasses"],
  music:     ["musicnotes","guitar","piano","trumpet","violin","drums"],
};

export const STICKER_FALLBACK = {
  leaf:"🍃",mushroom:"🍄",butterfly:"🦋",sunflower:"🌻",ladybug:"🐞",frog:"🐸",
  deer:"🦌",owl:"🦉",acorn2:"🌰",pinecone2:"🌲",fox:"🦊",hedgehog:"🦔",berries:"🍓",snail:"🐌",toadstool:"🍄",moss:"🌿",
  shell:"🐚",fish:"🐠",dolphin:"🐬",crab:"🦀",blowfish:"🐡",starfish:"⭐",
  octopus:"🐙",whale:"🐋",seahorse:"🐴",jellyfish:"🪼",turtle:"🐢",coral:"🪸",pearl:"🫧",sailboat:"⛵",lighthouse:"🏮",wave2:"🌊",
  sparkles:"✨",heartpink:"💗",star2:"🌟",catface:"😺",rainbowstar:"🌠",dango:"🍡",
  chibi:"🧸",sakuraPetal:"🌸",animeEyes:"👀",speedlines:"💨",blushing:"😊",sword2:"⚔️",ramen:"🍜",catears:"🐱",animeHeart:"💖",shuriken:"✴️",
  pumpkin:"🎃",ghost:"👻",bat:"🦇",skull:"💀",witch:"🧙",cauldron:"🧪",
  blackcat:"🐈‍⬛",spider:"🕷️",spiderweb:"🕸️",moon2:"🌕",frankenstein:"🧟",vampire:"🧛",potion:"🧪",eyeball:"👁️",bonez:"🦴",coffin:"⚰️",
  blossom:"🌸",rosered:"🌹",tulip:"🌷",bow:"🎀",peach:"🍑",fan:"🪷",
  torii:"⛩️",fuji:"🗻",maneki:"🐱",origami:"🦢",matcha:"🍵",onigiri:"🍙",
  planet:"🪐",rocket:"🚀",ufo:"🛸",comet:"☄️",moon:"🌙",alien:"👽",
  gamepad:"🎮",joystick:"🕹️",gem:"💎",sword:"⚔️",trophy:"🏆",pacman:"👾",
  pixelHeart:"❤️",pixelStar:"⭐",pixelCoin:"🪙",mushblock:"🍄",pixelCloud:"☁️",bomb:"💣",lightning2:"⚡",pixelCastle:"🏰",ghost2:"👻",pixelCrown:"👑",
  fallleaf:"🍂",mapleleaf:"🍁",chestnut:"🌰",haystack:"🌾",apple:"🍎",scarecrow:"🎃",
  acorn:"🌰",mushroom2:"🍄",squirrel:"🐿️",raindrop:"🌧️",candle:"🕯️",pie:"🥧",hotcoffee:"☕",pinecone:"🌲",sweater:"🧥",pumpkinpie:"🎃",
  mirrorball:"🪩",headphones:"🎧",microphone:"🎤",vinyl:"💿",disco_star:"🌟",dancer:"💃",
  neonlights:"💡",confetti:"🎊",rollerskate:"⛸️",taperecorder:"📼",boombox:"📻",diamond:"💎",lightbeam:"🔦",glitterball:"🪩",afro:"👩‍🦱",sunglasses:"🕶️",
  musicnotes:"🎶",guitar:"🎸",piano:"🎹",trumpet:"🎺",violin:"🎻",drums:"🥁",
};
